[[main]]
  identifier = "about"
  name = "about"
  url = "about"
  weight = 20

[[main]]
  identifier = "archive"
  name = "archive"
  url = "archive"
  weight = 21

[[main]]
  identifier = "gallery"
  name = "gallery"
  url = "gallery"
  weight = 22
    
[[main]]
  parent = "gallery"
  name = "cartoon"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "photo"
  url = "gallery/photo"

[[main]]
  identifier = "posts"
  name = "posts"
  url = "posts"
  weight = 23
    
[[main]]
  identifier = "notes"
  name = "notes"
  url = "notes"
  weight = 24